on:
  push:
  workflow_dispatch:

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate client
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: python-pydantic-v1
          config-file: config.yaml
          template-dir: templates

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: python-pydantic-v1-client
