on:
  push:
  workflow_dispatch:
jobs:
  generate-client:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate
        uses: MehdiRtal/openapi-python-client-action@994633aa75b82e6b89949c0ae515b426ab5947b8
        with:
          extra-args: 
            - "--output-path=./"
            - "--overwrite"
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v6
